FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL

RUN npm run build

FROM nginx:alpine


COPY --from=build /app/build /usr/share/nginx/html

# Если ты используешь React Router, нужна небольшая настройка Nginx, 
# чтобы при обновлении страницы не выдавало ошибку 404. 
# (Раскомментируй строку ниже и создай файл nginx.conf, если это потребуется позже)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Открываем 80 порт внутри контейнера
EXPOSE 80

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]